name: Build APK Server-Side

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer nos fichiers locaux
        uses: actions/checkout@v4

      - name: Installer Java sur le serveur
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installer Flutter sur le serveur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Créer le projet Flutter
        run: flutter create app_status

      - name: Injecter notre code
        run: cp code_application.dart app_status/lib/main.dart

      - name: Ajouter les packages propres
        run: |
          cd app_status
          flutter pub add image_picker ffmpeg_kit_flutter_min_gpl path_provider path

      - name: Configurer la version Android
        run: sed -i 's/flutter.minSdkVersion/24/g' app_status/android/app/build.gradle

      - name: Compiler l'APK
        run: |
          cd app_status
          flutter build apk --release

      - name: Livrer l'APK final
        uses: actions/upload-artifact@v4
        with:
          name: Mon-PureStatus-App
          path: app_status/build/app/outputs/flutter-apk/app-release.apk
