name: Build APK Server-Side

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer nos fichiers
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Créer le projet
        run: flutter create app_status

      - name: Injecter le code
        run: cp code_application.dart app_status/lib/main.dart

      - name: Ajouter les packages stables
        run: |
          cd app_status
          flutter pub add image_picker video_compress path_provider

      - name: Configurer SDK Android
        run: |
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 24/g' app_status/android/app/build.gradle
          sed -i 's/flutter.minSdkVersion/24/g' app_status/android/app/build.gradle

      - name: Compiler l'APK
        run: |
          cd app_status
          flutter build apk --release

      - name: Livrer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon-PureStatus-App
          path: app_status/build/app/outputs/flutter-apk/app-release.apk
